name: deploy to pages
on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: npm
      - name: checkout
        uses: actions/checkout@v4
      - name: configure pages
        id: pages
        uses: actions/configure-pages@v4
      - name: install npm deps
        run: npm ci
      - name: build
        run: npm run build
      - name: upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: deploy to pages
        id: deployment
        uses: actions/deploy-pages@v4
